# -*- coding: utf-8 -*-
"""Crop_production_data

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BbU2WDPMiwLL9HKxWqmEuruQhXpNPfkC

import all the libraries with corresponding variables
"""

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

data=pd.read_csv("Crop Production data.csv")

data.shape

data.info()

data.describe()

data.head()

"""here seaborn(sns) is used to visualize random distributions. Basically abt to plot the grphs """

plt.figure(figsize=(14,7))
plt.title("Finding the Correlation")
sns.heatmap(data.corr(),annot=True)

plt.hist(data['Crop'],rwidth=,color='pink')
plt.title("Crop")
print(plt)

plt.hist(data['Area'],rwidth=1.0,color='purple')
plt.title("Area")
print(plt)

plt.figure(figsize=(10,5))
plt.hist(data['Crop_Year'],bins=20,rwidth=0.8)

print(plt)